import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import localFont from 'next/font/local'
 
// Font files can be colocated inside of `pages`
const myFont = localFont({ src: '../../public/fonts/Chillow-PersonalUse.ttf',
  variable: "--font-Chillow-PersonalUse",
  weight: '400',
 })

 

 const myFontOne = localFont({ src: '../../public/fonts/Spot-Normal.ttf',
  variable: "--font-Spot-Normal",
  weight: '400',
 })

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${myFont.variable} ${geistMono.variable} antialiased`}
        className={`${myFont.variable} ${myFontOne.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
